#!/usr/bin/env bash
set -euo pipefail

OUTPUT=".env"

# Helpers

section() { echo ""; echo "$*:"; }

# Prompt for a value, accepting a default. Required if no default given.
ask() {
  local -n _ref="$1"
  local label="$2"
  local default="${3:-}"
  local hint="${4:-}"

  [[ -n "$hint" ]] && echo "  ($hint)"

  if [[ -n "$default" ]]; then
    read -rp "  $label [$default]: " _ref
    _ref="${_ref:-$default}"
  else
    read -rp "  $label: " _ref
    while [[ -z "$_ref" ]]; do
      echo "  Required - cannot be empty."
      read -rp "  $label: " _ref
    done
  fi
}

# Same as ask but input is hidden (for secrets)
ask_secret() {
  local -n _ref="$1"
  local label="$2"

  read -rsp "  $label: " _ref
  echo ""
  while [[ -z "$_ref" ]]; do
    echo "  Required - cannot be empty."
    read -rsp "  $label: " _ref
    echo ""
  done
}

# Guard

echo "GatoNet - .env generator"
echo "Press Enter to accept the detected or default value."

if [[ -f "$OUTPUT" ]]; then
  read -rp "$OUTPUT already exists. Overwrite? [y/N]: " _confirm
  [[ "${_confirm,,}" == "y" ]] || { echo "Aborted."; exit 0; }
fi

# Identity

section "Identity"

ask PUID "PUID" "$(id -u)" "numeric user ID - run 'id \$(whoami)' to verify"
while ! [[ "$PUID" =~ ^[0-9]+$ ]]; do
  echo "  Must be a number."
  ask PUID "PUID" "$(id -u)"
done

ask PGID "PGID" "$(id -g)"
while ! [[ "$PGID" =~ ^[0-9]+$ ]]; do
  echo "  Must be a number."
  ask PGID "PGID" "$(id -g)"
done

_detected_tz=""
if [[ -f /etc/timezone ]]; then
  _detected_tz=$(< /etc/timezone)
elif command -v timedatectl &>/dev/null; then
  _detected_tz=$(timedatectl show --property=Timezone --value 2>/dev/null || true)
fi
ask TZ "Timezone" "${_detected_tz:-UTC}" "e.g. America/Sao_Paulo, Europe/Oslo"

# Paths

section "Paths"

ask CONFIG_PATH "Config path" "/opt/gatonet/config" "container state and config"
ask DATA_PATH   "Data path"   "/opt/gatonet/data" \
  "downloads + media in one filesystem so Radarr/Sonarr can hardlink instead of copy"

# VPN provider

section "VPN provider"

echo "  1) mullvad   (recommended)"
echo "  2) nordvpn"
echo "  3) protonvpn"
echo "  4) other"
read -rp "  Choose [1]: " _choice
_choice="${_choice:-1}"

case "$_choice" in
  1) VPN_SERVICE_PROVIDER="mullvad" ;;
  2) VPN_SERVICE_PROVIDER="nordvpn" ;;
  3) VPN_SERVICE_PROVIDER="protonvpn" ;;
  4) ask VPN_SERVICE_PROVIDER "Provider name" "" \
       "see https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers" ;;
  *) echo "Invalid choice, defaulting to mullvad."; VPN_SERVICE_PROVIDER="mullvad" ;;
esac

# NordVPN exposes service credentials (username + password) for manual setup,
# not a WireGuard private key. Use OpenVPN for NordVPN; WireGuard for others.
if [[ "$VPN_SERVICE_PROVIDER" == "nordvpn" ]]; then
  VPN_TYPE="openvpn"
else
  VPN_TYPE="wireguard"
fi

# Credentials

section "VPN credentials"

if [[ "$VPN_SERVICE_PROVIDER" == "nordvpn" ]]; then
  echo "  Find these at: account.nordvpn.com > Manual setup > Service credentials"
  echo ""
  ask         OPENVPN_USER     "Username"
  ask_secret  OPENVPN_PASSWORD "Password"
  WIREGUARD_PRIVATE_KEY=""
  WIREGUARD_ADDRESSES=""
else
  echo "  Find these in your VPN provider's account panel."
  echo ""
  ask_secret WIREGUARD_PRIVATE_KEY "Private key"
  ask WIREGUARD_ADDRESSES "WireGuard address" "" "e.g. 10.64.x.x/32 (shown next to your key in the provider panel)"
  OPENVPN_USER=""
  OPENVPN_PASSWORD=""
fi

ask VPN_SERVER_COUNTRIES "VPN exit country" "Netherlands"

# Write .env

{
  echo "# Generated by generate-env.sh - $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo ""
  echo "# Identity"
  echo "PUID=${PUID}"
  echo "PGID=${PGID}"
  echo "TZ=${TZ}"
  echo ""
  echo "# Paths"
  echo "CONFIG_PATH=${CONFIG_PATH}"
  echo "DATA_PATH=${DATA_PATH}"
  echo ""
  echo "# VPN"
  echo "VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}"
  echo "VPN_TYPE=${VPN_TYPE}"
  [[ -n "$OPENVPN_USER" ]]             && echo "OPENVPN_USER=${OPENVPN_USER}"
  [[ -n "$OPENVPN_PASSWORD" ]]         && echo "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
  [[ -n "$WIREGUARD_PRIVATE_KEY" ]]    && echo "WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}"
  [[ -n "$WIREGUARD_ADDRESSES" ]]      && echo "WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}"
  echo "VPN_SERVER_COUNTRIES=${VPN_SERVER_COUNTRIES}"
} > "$OUTPUT"

chmod 600 "$OUTPUT"

echo ""
echo "Written to $OUTPUT (chmod 600 - readable only by you)"
echo ""
echo "Next steps:"
echo "  sudo bash setup.sh"
echo "  docker compose up -d"
